//
// resource.h
//
// Generated by C DriverWizard 3.2.0 (Build 2485)
// Requires DDK Only
// File created on 10/4/2005
//

#define IDD_COINST_DIALOG               200

#define IDC_CLONE_ENABLE                1000
