// intrface.h
//
// Generated by C DriverWizard 3.2.0 (Build 2485)
// Requires DDK Only
// File created on 9/16/2005
//

// Define an Interface Guid for SerialClone device class.
// This GUID is used to register (IoRegisterDeviceInterface)
// an instance of an interface so that user application
// can control the SerialClone device.
//
//  {E705CB6F-46DF-4582-85D2-341F4E720E48}
DEFINE_GUID(GUID_DEVINTERFACE_SERIALCLONE,
    0xE705CB6F, 0x46DF, 0x4582, 0x85, 0xD2, 0x34, 0x1F, 0x4E, 0x72, 0x0E, 0x48);

// GUID definition are required to be outside of header inclusion pragma to avoid
// error during precompiled headers.
//

#ifndef __INTRFACE_H__
#define __INTRFACE_H__

#define FILE_DEVICE_SERIALCLONE  0x8000

// Define Interface reference/dereference routines for
// Interfaces exported by IRP_MN_QUERY_INTERFACE

#define SERIALCLONE_IOCTL(index) \
    CTL_CODE(FILE_DEVICE_SERIALCLONE, index, METHOD_BUFFERED, FILE_READ_DATA)


#endif // __INTRFACE_H__
