//
// SerialCloneApp.h
//
// Generated by C DriverWizard 3.2.0 (Build 2485)
// Requires DDK Only
// File created on 10/4/2005
//
#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <process.h>
#include <commctrl.h>
#include <tchar.h>
#include <setupapi.h>
#include <initguid.h>
#include <winioctl.h>
#include <process.h>
#include <assert.h>
#include <dbt.h>
#include "resource.h"

#include "..\intrface.h"

#define MAX_STRING_LENGTH       500

typedef VOID (*SERIALCLONE_IO_CALLBACK)(PVOID Context);

// Structure used to store I/O information for delayed
// processing of overlapped requests
typedef struct _SERIALCLONE_LIST_ITEM
{
    struct _SERIALCLONE_LIST_ITEM*  Next;
    struct _SERIALCLONE_LIST_ITEM*  Previous;
    OVERLAPPED                  IoOverlapped;
    PCHAR                       InBuffer;
    PCHAR                       OutBuffer;
    ULONG                       InSize;
    ULONG                       OutSize;
    ULONG                       ReturnLength;
    ULONG                       Error;
    SERIALCLONE_IO_CALLBACK         Callback;
} SERIALCLONE_LIST_ITEM, *PSERIALCLONE_LIST_ITEM;

extern HANDLE           g_hDevice;
extern SERIALCLONE_LIST_ITEM    g_IoList;
extern CRITICAL_SECTION g_IoListLock;

ULONG SerialCloneExecuteIo(HWND hDlg);
UINT __stdcall SerialCloneIoCompletionThread(PVOID Context);
VOID SerialCloneOutputText(LPCTSTR Format, ...);
VOID SerialCloneOutputBuffer(PVOID Buffer, ULONG Size);

