// SerialClone.h
//
// Generated by C DriverWizard 3.2.0 (Build 2485)
// Requires DDK Only
// File created on 9/16/2005
//
#ifndef __SERIALCLONEDLL_H__
#define __SERIALCLONEDLL_H__

extern "C"
{

DWORD Install(void);
DWORD Uninstall(void);
HRESULT SerialCloneCoInstall(
    IN DI_FUNCTION  InstallFunction,
    IN HDEVINFO  DeviceInfoSet,
    IN PSP_DEVINFO_DATA  DeviceInfoData  OPTIONAL,
    IN OUT PCOINSTALLER_CONTEXT_DATA  Context
    );

}

#endif // __SERIALCLONEDLL_H__
