// pch.h
//
// Generated by C DriverWizard 3.2.0 (Build 2485)
// Requires DDK Only
// File created on 9/16/2005
//
#ifdef __cplusplus
extern "C" {
#endif // __cplusplus
#pragma warning(disable:4200)   // nonstandard extension used : zero-sized array in struct/union
#pragma warning(disable:4201)   // nonstandard extension used : nameless struct/union
#include <stdarg.h>
#include <stdio.h>
#include <stddef.h>
#include <initguid.h>
#include <wdm.h>
//#include <ntddk.h>
#include <wmilib.h>
#include <wmistr.h>
#define NTSTRSAFE_LIB
#include <ntstrsafe.h>
#ifdef __cplusplus
}
#endif // __cplusplus
#include "SerialClone.h"
